import os

COPPERNICUS_CLIENT_ID = os.getenv('COPPERNICUS_CLIENT_ID')
COPPERNICUS_CLIENT_SECRET = os.getenv('COPPERNICUS_CLIENT_SECRET')


POSTGRES_HOST = os.getenv('POSTGRES_HOST')
POSTGRES_PORT = os.getenv('POSTGRES_PORT')
POSTGRES_USER = os.getenv('POSTGRES_USER')
POSTGRES_PASSWORD = os.getenv('POSTGRES_PASSWORD')


